#!/bin/bash

while true; do
    batterycharge=$(cat /sys/class/power_supply/BAT0/capacity)
    batterystatus=$(cat /sys/class/power_supply/BAT0/status)
    wifi=$(nmcli device wifi | grep -E '^[*]' | awk -F '[[:space:]][[:space:]]+' '/*/ {print $8}')
    xsetroot -name " $wifi | $batterystatus $batterycharge% | $(date +'%a %b %_d - %I:%M:%S %p')"
    sleep 1
done
