#!/bin/bash

while true; do
    batterycharge=$(cat /sys/class/power_supply/BAT0/capacity)
    # batterystatus="C" && [[ $(cat /sys/class/power_supply/BAT0/status) == "Discharging" ]] && batterystatuschar="D"
    batterystatus=$(cat /sys/class/power_supply/BAT0/status)
    wifi=$(nmcli device wifi | grep -E '^[*]' | awk '/*/ {print $9}')
    xsetroot -name " $wifi | $batterystatus $batterycharge% | $(date +'%a %b %_d - %I:%M:%S %p')"
    sleep 1
done
