#!/bin/sh

tmux switch-client -t config
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c ~/.config -d -s config -n config && tmux switch-client -t config
tmux neww -n zsh -c ~ nvim .zshrc
tmux neww -n tmux -c ~ nvim ~/.tmux.conf
tmux neww -n xmonad -c ~/.xmonad nvim xmonad.hs
tmux select-window -t 1
