#!/bin/sh

dirname=`basename $1`

tmux switch-client -t $dirname
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $1 -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $1 -A -s $dirname
